# fly.toml app configuration file generated for smileys-development on 2023-06-26T15:09:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smileys-development"
primary_region = "arn"

[env]
  ENVIRONMENT = "DEVELOPMENT"
  ORIGIN = "*"
  PORT = "8020"
  DATABASE_URL=mongodb+srv://smileysfuturice:rGIXYwBzVmki0mUf@smileys.hhpox1q.mongodb.net/Development?retryWrites=true&w=majority

[http_service]
  internal_port = 8020
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "Dockerfile"